name: Execute static code analysis

on: [ push ]

jobs:
  staticcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Static check
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.6"
